
services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ROOT_PASS: ${ROOT_PASS}

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wp
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASS=${WP_USER_PASS}
      - WP_USER_EMAIL=${WP_USER_EMAIL}

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

volumes:
  db_data:
    name: "db_volume"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/adrherna/data/db

  wp_data:
    name: "wp_volume"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/adrherna/data/db

networks:
  inception:
