FROM debian/bullseye

RUN apt update && apt install -y mariadb-server && rm -rf /var/lib/apt/lists/*
RUN sed -i "s/bind-address\s*=.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf

COPY init-db.sh /init-db.sh
COPY .env /.env
RUN chmod +x /init-db.sh

RUN /init-db.sh

CMD ["/usr/bin/mysqld_safe"]